### ISSUE TITLE
Only in RDP sessions

### ISSUE THREAD

**Issue by fullenw1** [Crypt32/PSPKI#14]
Hi,

First of all many thanks for the time you passed writing all this useful cmdlets.

In fact, I work most of my time through PSSessions within ISE, and I rarely open an RDP session.
Thus it took me some time to realize that some cmdlets are not working in PSSessions, and that I had to open an RDP session on the CA server directly. For example, Get-CertificationAuthority just returns nothing.

Please could you add a warning when the PSPKI module is loaded in a PSSession?
Thanks!

**Comment by Crypt32** [comment]
> I had to open an RDP session on the CA server directly.

well, the module is intended to avoid this. Literally all CA management commands allow you to manage CA remotely, from your PC. You just install the module on your PC, install ADCS RSAT and execute commands locally. No need to install the module directly on CA server.

**Comment by fullenw1** [comment]
You are right, it works fine on my local workstation (like in an RDP session).
It's strange that it doesn't work in a PSSession on a CA...

Thanks again for your great work!

**Comment by Crypt32** [comment]
It doesn't work due to double-hop issue. Get-CA command makes external calls to AD and CA server and requires credential delegation (or CredSSP authentication package). This is why I do not recommend to run the module in remoting sessions. You should be able to do all remote stuff from your local PC. This is what the module is intended for.

**Comment by fullenw1** [comment]
Thank you Vadims!
