### ISSUE TITLE
Get-CertificationAuthority under non-administrative user account

### ISSUE THREAD

**Issue by acidmind** [Crypt32/PSPKI#18]
Hello.
When we use the command Get-CertificationAuthority under non-administrative user account, but with right "Issue and Manage Certificates" on CA, we get a delay of about 3 seconds.

Our CA has Enterprise Subordinate type, runs on a Windows Server 2012 R2 and we are using version 3.2.6 of your module.

Please help us to solve this problem.
Thank you!

**Comment by Crypt32** [comment]
Delays can be caused by the code that checks certain things and fails due to insufficient permissions. Though, 3 sec delay for PowerShell is not significant and can be caused by external reasons.

**Comment by acidmind** [comment]
Thanks for your reply!
Can you please take an advice how we can minimize delays while code checking certain things. Maybe code will not be fail if we grant access to some WMI class or AD object?
If I connect through COM objects there is no such problem.
$ CaView = New-Object -ComObject CertificateAuthority.View
$ CaView.OpenConnection ("testca1 \ test CA")
I want to implement an API based on PS JEA and a PSPKI module, a delay of 3 seconds will be a lot.

It would be a good idea to have a key that excludes these checks, for example
Get-CertificationAuthority -ComputerName testca1 -NoAdmin. :-)

**Comment by Crypt32** [comment]
`Get-CertificationAuthority` cmdlet collects various information from various sources about CA server which is necessary for further logc. Cmdlet connects to AD to enumerate CAs, detect each CA, resolve OIDs and so on. When connecting to CA (it is another source), cmdlet attempts to use various communication channels to get the information. For example, it attempts to get config by using remote registry and if remote registry fails, it attempts to communicate via RPC/DCOM. There are too many places where you can get delays. If you can, you may need to debug DLL code with profiler.

Since all collected information is required, there is no way to exclude these checks (actually, information collection).

> If I connect through COM objects there is no such problem.

yes, because you do not do extra work that my code does. The only thing I can suggest is to profile my DLL code.

**Comment by acidmind** [comment]
After doing the trace, I found out that the cmdlet hangs by calling the PKI.Utils.WMI.GetWMI method. This method tries to connect to the WMI namespace root\CIMv2. 
And the problem was solved when I gave the right "Enable Account", "Remote Enable" on this namespace on the CA server.
**Thanks very much!**
