### ISSUE TITLE
Sync with codeplex

### ISSUE THREAD

**Issue by jalliot** [Crypt32/PSPKI#2]
Hello Vadims!

Great 3.2.6 release! It fixes all bugs/problems I raised since the 3.2.5 :)

Just note that this repo is not synced with the release on codeplex (the PSD1 file still mentions 3.2.5.0 for instance and the libraries have not been updated).
You might have to re-think your release process since the move to a public repo ;-) Someone taking raw sources from here might have problems difficult to identify otherwise.

In my case, I don't like the installer for instance and always preferred to download the sources from codeplex (which you have not made available this time probably because of the move to github).

**Comment by Crypt32** [comment]
Thanks for reminder. I really forgot to sync this repo. Now i fixed this. The problem with PSPKI module release is that too many things must be done prior to publishing it online:

- run tests for ASN parser, make release build and copy to PSPKI development folder. Commit changes to public repo.
- compile API's xml-doc to HTML and copy to web site. Update them if something is missing, rebuild the project.
- run tests for PKI.Core.dll, make release build and copy to PSPKI development folder. Commit changes to public repo.
- compile API's xml-doc HTML and copy to web site. Update them if necessary, rebuild the project.
- copy PSPKI development folder for local tests, write module help and publish it online and update local sources.
- sync all modified files and prepare for signing. Commit changes to public repo.
- create installer for signed module and test if it works as expected
- publish module to CodePlex and write a blog post to describe most notable changes.

the process looks not so hard, but in reality, I have to maintain four separate VS projects: PSPKI, ASN parser, PKI library and PS Cmdlet Help Editor (I'm still updating PS Cmdlet Help Editor to meet my needs), three web sites with documentation (for each project) and all of them must be in sync and it is hard to automate any of these steps. I have a full-time job and can work on these projects only when I have free time. As the result, the whole process described above might take 2-3-4 full evenings and I can miss something from the list.

Regarding sources. I moved to GitHub because I can publish interrelease changes and rapid fixes to users who do not care about official releases.
Another intent is to provide better code review and analysis by community (and collaboration through pull requests). I'm still maintaining project on CodePlex, because it provides better UX for standard users and IT Pro (many of IT Pros doesn't understand GitHub concept and prefer more user-friendly UX like CodePlex). Official discussion and bug submission channel is still on CodePlex.

Several years ago, when the module was available as a source-only package, I constantly received a lot of questions about module installation from IT Pros with very basic PowerShell experience. So I made convenient and user-friendly installer my priority and installer is main module distribution path.
I think you are right, it is still recommended to ship module sources (with compiled DLLs) along with installer because there still are users with high level of paranoya and internal security policies (since the module works with security technologies) and they may not allowed to use installer. Another reason is that GitHub repos are not always in sync with official releases because of interrelease changes. So I added sources to CodePlex release page.

HTH

**Comment by jalliot** [comment]
Don't worry I know what this is!
I think most of those tasks could be automated in some way (except for the blog post of course...). But that would probably take you quite a lot of time probably better spent elsewhere... :smile: 

Thanks for syncing anyway.
