### ISSUE TITLE
Make database queries and objects in general timeout-aware

### ISSUE THREAD

**Issue by jalliot** [Crypt32/PSPKI#23]
I am not sure this is even possible to handle so this issue is for discussion purpose mostly.
I am using your library and module on "relatively large" CA databases (about half a million rows at the time of writing for my highest volume CA) and wrote some scripts that are run via scheduled tasks in order to generate reports, send notification emails, etc.

My problem is that the scripts are taking more and more time to execute the more the database grows (that is expected), leading to what appears to be timeout issues. For example one reporting script queries over almost all of the records, does some filtering on user-side (because of the poor filtering capabilities of AD CS API) and for each record does some relatively heavy processing (additional database queries, some AD + DNS + Exchange checks and so on), before moving on to the next record.
If I just make this one big query, the connection to the CA (or the COM object I don't know) fails at some point, which led me to slice the query (at the moment 10,000 records at a time only).

This is mostly working but more difficult to write/maintain and it is now taking forever to execute for some of those tasks...
I even replaced some of them with pure certutil-based queries (with its output mode to CSV) because this is just incredibly faster. I know .NET/PowerShell code can't be as efficient as C code like certutil, especially when working with COM classes but this made me wonder if it was possible to a) speed the library a little (unlikely I guess) and b) at least make it "timeout-aware", i.e. capable of transparently handling dropped connections to the COM class/underlying CA and automatically re-establishing the connection, without any developer action.

In the meantime, we are looking for a solution that would extract the databases of several CAs to a single location with real SQL-like capabilities and that would probably make all of this unnecessary but that is another (and maybe utopic) subject :)

**Comment by Crypt32** [comment]
Marking this as "won't fix" because there is nothing I can do. Unfortunately.

Why certutil dumps CA database quickly? JET database engine is written in C++ (unmanaged world), certutil is written in C++ (unmanaged world) too. It's the best case. PowerShell, on the other hand is .NET-based, which means managed world (with garbage collection). Data marshalling between RCW (runtime callable wrapper) and CCW (COM-callable wrapper) gives you serious performance penalty. And keep in mind that PowerShell gives you a reasonable performance penalty.

Even if I attempt to write native C++ code to access CA database, I still will have to marshal data in order to use it in .NET/PowerShell.

> In the meantime, we are looking for a solution that would extract the databases of several CAs to a single location with real SQL-like capabilities and that would probably make all of this unnecessary but that is another (and maybe utopic) subject

I worked once on this. The idea was:
1) dump current CA database to SQL by using existing tools (certutil, .NET/PowerShell). You can do it in chunks just to not fall into DCOM connection timeout.
2) once database is dumbed, new records should be written to SQL by using custom ExitModule, so new database records are pushed to SQL automatically.

So this is certainly doable in a reasonable timeframe.

---------------------------------------------------------------
I have a private ExitModule draft written in C# (CLR) for my own purposes. However, this never went anywhere further because of time. I have a full-time job, studying in University, having my own stuff, open source projects and so on. Unfortunately, I failed to find someone who would be the same passionate in CryptoAPI (and an ability to make it more available in .NET/PowerShell) to cooperate with on a free basis. PSPKI project started in 2011 (when I publically released first version v0.8) and still running it alone.

**Comment by jalliot** [comment]
Don't worry as I said this was mostly for discussion purpose, I fully understand the difficulty of this and most of all that you are working on this on your free time (and I think I speak for many if I say we are very grateful with you for that!).

Speed aside (you just confirmed what I highly suspected), what are your thoughts about being "timeout-aware"? I'm no expert in DCOM so this is maybe unfeasible but if it was (without requiring a complete code rewrite of course), this could greatly enhance the usability of the library for large CAs.

As for the exit module, I thought about writing one myself some time ago but clearly lack the time and knowledge (to be honest I didn't even know we could write one in C#... I thought only C++ would do).
I find it strange that Microsoft only has MIM CLM (which is almost useless in my opinion) and never found it interesting to try to sell a real RA+reporting product... (and yes i said sell because I don't expect such features to come freely as part of native Windows features...)

**Comment by Crypt32** [comment]
> I'm no expert in DCOM so this is maybe unfeasible but if it was (without requiring a complete code rewrite of course), this could greatly enhance the usability of the library for large CAs.

Not sure if you are asking this, but ICertView COM interface provides customizable access timeout setting. Default value is 10 minutes. If you are expecting to run a long-rinning single query, you may want to adjust this timeout setting (by increasing it). Or you can split the query to query the database in chinks. Say, by querying 10k or 50k (it is just an example) rows per query.

> I didn't even know we could write one in C#

I didn't too until I was forced to dive into it. Years ago I installed Enterprise CA on Server Core. However, I discovered that SMTP Exit Module doesn't work on Server Core installations, because mail module (which is a dll with basic COM interfaces from Exchange 5.5) is missing. So I made several attempts and was able to write a PoC Exit Module in C# to add support for mails in Server Core installations.

Yes, ILM 2007, Forefront CLM and now MIM CLM (which ship SQL Exit Module) aren't much useful. And buying entire product just for extra basic functionality isn't a good idea either. If you have internal developers, they should be able to write the desired Exit Module in .NET (though, with a ton of pitfalls).

**Comment by Crypt32** [comment]
> Didn't know about this setting.

these settings are part of CA configuration There are two entries: `ViewAgeMinutes` and `ViewIdleMinutes`. But their change requires CA service restart which is not acceptable in our scenario. This is why I haven't bothered with this at all.

> do you think this splicing of queries could be managed transparently by your library, based on the current timeout settings.

no. Chunking may work around possible timeout issues with a sort of ugly design. That is, run a series of queries which will query a chunk of records, for example: first 50k rows, second 50k rows (from 50k to 100k), 3rd 50k rows (from 100k to 150k), etc. The biggest issue is to get upper limit for RowID. Internal sorting has awful performance, so it is not a reliable solution to get upper limit. There is no function like `count(*)` to get estimated number of rows in a table. This issue requires deep research in order to get more or less efficient solution.

> and automatically create a new connect when the timeout value is reached

timeout is individual for each connection. Once we call `$CaView.OpenConnection()` a timeout timer starts after each subsequent DB call by `$CaView` object. If you instantiate another connection (say, `$CaView2.OpenConnection()`, it won't affect our first connection. We have to refresh connection by our original `$CaView` connection. Since it awaits for response, you can't refresh the connection in the same thread. You may need to run it in background as a separate thread (maybe, as AsJob).

In CA database access code I made nearly all the best I could do in terms of performance. Though, there is one thing to improve -- get rid of `Add-Member` cmdlet and move to `Properties` dictionary (and break all existing scripts). But that's all.

**Comment by jalliot** [comment]
Hello Vadims,
Sorry to bring back this topic but couldn't find a way to private message you.
Would it be possible for you to share the draft of the private C# exit module you mentioned in this thread (in a gist maybe)? I understand it was not finished and of course you can anonymize it if required, I would just like to see the general structure/requirements.

I managed to decompile the policy and exit modules of MIM 2016 so I should be covered to write my own but a real un-decompiled example might still be helpful :)
If you've done the same for a policy module, that would even be better (and yet better if it links with the Microsoft default policy module like MIM one does).

**Comment by Crypt32** [comment]
You can reach me privately via my website's contact form.
