### ISSUE TITLE
Remove Write-Host from Get-EnterprisePKIHealthStatus

### ISSUE THREAD

**Issue by TDabasinskas** [Crypt32/PSPKI#4]
Hi,

As per the best practices, cmdlets should not be using Write-Host function to display any output. Anyhow, it seems that `Get-EnterprisePKIHealthStatus` cmdlet does not comply with that, always outputting the CA name due to the following line:

``` powershell
Write-Host ("=" * 20) $CA.DisplayName ("=" * 20)
```

Is it possible to remove this line, convert it to Write-Verbose or introduce an additional switch parameter which would allow to suppress it?

Thank you.

**Comment by Crypt32** [comment]
Looks like it is an artifact from my early POCO version. Although, there is a such recommendation to not use Write-Host, I'm still using it in several cmdlets because there is no better way to respond to user.

However, this issue is not the case and I fixed it in https://github.com/Crypt32/PSPKI/commit/3aab19f8047c17111d19a2789e1ca79f56ba6ba9. I will work further to remove all ambigous Write-Host occurences. For consistency puproses, please open the "Write-Host" and "Write-Warning" issues against the following commands. so I'll be able to track them:
```
Approve-CertificateRequest
Get-RequestRow
Remove-CAKRACertificate
Revoke-Certificate
Remove-CertificateEnrollmentPolicyService
Remove-CertificateEnrollmentService
Remove-DatabaseRow
Deny-CertificateRequest
Add-CertificateEnrollmentService
Add-CertificateEnrollmentPolicyService
Add-CertificateTemplateAcl
```
You are not required to close this issue, because I'll close it when publishing next module release.

**Comment by TDabasinskas** [comment]
Thanks, @Crypt32! Is there actually a reason you would suggest removing `Write-Warning` as well? As far as I know, this one is OK to use (which is not the case with `Write-Host`).

**Comment by Crypt32** [comment]
> Is there actually a reason you would suggest removing  Write-Warning  as well?

yep. The module was created long ago before there guidelines were created (2009, or 2010). Originally, PowerShell community suggested to use `Write-Warning` instead of `Write-Error` to indicate error messages. There are several parts that are unchanged from that time, I think that it is better to throw errors when appropriate instead of `Write-Warning`. The functions I mentioned use this outdated behavior to indicate various sorts of errors or status messages,

**Comment by Crypt32** [comment]
I mean that `Write-Warning` will remain where it is appropriate (when the cmdlet notifies about further required steps), but definitely must be changed where it is used to indicate error state. These occurences should be changed with `throw` statement,

**Comment by TDabasinskas** [comment]
Thanks for the clarification. I am going to open a separate issue to have this fixed in the functions you listed.

**Comment by Crypt32** [comment]
Yes, please do. I checked listed functions and it appears that `Write-Warning` there is not appropriate there and `throw` statement should be used instead.

**Comment by Crypt32** [comment]
The work is in progress in this branch: https://github.com/Crypt32/PSPKI/tree/feature-WriteHostCompliance

**Comment by FLeven** [comment]
I am not sure if this back and force, between Write-X (#4, #5 ) an efficient approach. I can only add, that in a Desired State Configuration / Alternatives world  (where we stop to use code in production environemnents, in an interactive fashion and output/report errors different streams), I would like to work with your Module(s) instead of what is available as of today. For example the carbon module managed to to be one solution for both worlds and managed to be usefull in designing an environment line by line or in pushing out the result as a DSC configuration in the end.
