### ISSUE TITLE
Generating a self-signed certificate, in memory only, without admin access

### ISSUE THREAD

**Issue by KirkMunro** [Crypt32/PSPKI#40]
Hi @Crypt32! I'm looking for an easy way to generate a self-signed certificate in memory, without requiring elevation. Will New-SelfSignedCertificateEx allow me to do this? Or does it work like New-SelfSignedCertificate, automatically writing the certificate to the cert store (and therefore requiring elevation)?

**Comment by Crypt32** [comment]
what do you mean under "elevation"? If you mean UAC to enable priveleges, then you can avoid generating the certificate in local machine store and use current user store which doesn't require any sort of elevation.

With CertEnroll it is impossible to avoid interaction with certificate store. It is possible to not touch cert store with `CertCreateSelfSignCertificate` function.

**Comment by KirkMunro** [comment]
Of course! I didn't notice the script I was working with was configured to use the Local Machine store *sigh* Chalk it up to Monday morning fog. Thanks Vadims!

**Comment by KirkMunro** [comment]
Ok, so I need some additional details about New-SelfSignedCertificateEx. While using the CurrentUser store removes the need for elevation, I'm still having troubles. My issue is that I'm using an Azure Function to generate a self-signed certificate, and the Azure Function architecture denies access to all certificate stores, so I get access denied even when using the CurrentUser store.

My next thought is to go back to generating it in memory, using a temporary certificate store that is generated in memory as well (which would require using PInvoke with the CertOpenStore Win32 API, passing in the CERT_STORE_PROV_MEMORY flag, and then passing the resulting HCERTSTORE IntPtr into the X509Store constructor -- this is partially described [here](https://docs.microsoft.com/en-us/windows/desktop/SecCrypto/example-c-program-certificate-store-operations)). @Crypt32: Does New-SelfSignedCertificateEx support anything like this, with the certificate being generated in memory with an in-memory certificate store?

**Comment by Crypt32** [comment]
> Does New-SelfSignedCertificateEx support anything like this, with the certificate being generated in memory with an in-memory certificate store?

not now. Like I said, I'm using CertEnroll which requires interaction with persistent certificate store. The only way to do this is to use `CertCreateSelfSignCertificate` function. To reduce the amount of p/invoke you can use most parts of CertEnroll and before calling `CertCreateSelfSignCertificate` function convert the data to compatible format.

If it is urgent -- use 3rd party tools to generate the certificate at runtime. Otherwise and if there is value, I can put it in next release.

p.s. even though my function has two parametersets, they are a bit flawed

**Comment by KirkMunro** [comment]
Ok, now I follow what you were pointing out when you mentioned CertEnroll. When are you planning your next release?

**Comment by Crypt32** [comment]
Next release is not yet scheduled, but I would suspect that by the end of July. I have a lot of things to do for next release.

**Comment by KirkMunro** [comment]
Good to know. Thanks Vadims.

**Comment by Crypt32** [comment]
Well, the task was a bit more complicated than I expected. Though, I've completed core functionality: https://github.com/Crypt32/pkix.net/blob/feature-CertGenerator/PKI/Cryptography/X509Certificates/X509CertificateBuilder.cs

Due to a lack of time, PowerShell wrappers are not yet available. Well, the usage is quite simple:

1) instantiate `X509CertificateBuilder` class
2) fill properties you need. For example, specify subject, validity, signature algorithm, provide extensions if necessary.
3) configure private key generation options in `PrivateKeyInfo` property
4) run `Build()` method to create a self-signed certificate. This method optionally accepts an `X509Certificate2` object that can be used as a signer to make externally signed certificate. If null, a self-signed certificate is created.

By default, only subject key identifier (and authority key identifier when appropriate) extension is added. The rest extensions must be supplied by a caller. This is all I can offer you today.

**Comment by KirkMunro** [comment]
Thank you Vadims, I appreciate this effort (and sorry for the delayed reply -- I just came back from vacation and saw this today).

**Comment by Crypt32** [comment]
No worries, I was busy with other stuff last month and didn't proceed much since last time. I finished C# library code and just started PS code writing.

**Comment by Crypt32** [comment]
PowerShell code is done in respective branch: https://github.com/Crypt32/PSPKI/blob/feature-40-SelfSignCertInMemory/PSPKI/Client/New-SelfSignedCertificateEx.ps1

I can provide compiled dll file for testing If you are interested.

**Comment by Ajay250496** [comment]
Looking for this exact functionality. Downloaded the feature branch and imported it, but getting this error
`The following error occurred: Cannot find type [SysadminsLV.PKI.Cryptography.X509Certificates.X509CertificateBuilder]: verify that the 
assembly containing this                                                                                                                      assembly containing this
     | type is loaded.`

Any idea how I can solve it?
