### ISSUE TITLE
Can the docs explain the difference between PSPKI and PKI modules?

### ISSUE THREAD

**Issue by mikemaccana** [Crypt32/PSPKI#48]
Heya! I'm having trouble understanding the relationship of this module to the inbuilt one in Powershell 5. 
 - Is `PSPKI` an updated version of `PKI`, or a new codebase?
 - Why is `New-SelfSignedCertificateEx` called `New-SelfSignedCertificateEx` when it is `New-SelfSignedCertificate` in `PKI`? Is that so I could have them both installed simultaneously? 

`Get-Command -module PKI` on PS5 and `Get-Command -module PSPKI` show there's some overlap and some difference, but it would be great if README.md explained it better.

**Comment by Crypt32** [comment]
>Is PSPKI an updated version of PKI, or a new codebase?

PSPKI is a completeley separate codebase. In fact, PSPKI module was developed long ago prior to Microsoft's PKI module. PKI module is developed and maintained by Microsoft, PSPKI is developed and maintained by me.

> Why is New-SelfSignedCertificateEx called New-SelfSignedCertificateEx when it is New-SelfSignedCertificate in PKI?

because these are different commands with similar purpose. Originally, my command was called `New-SelfSignedCertificate`. However, after release of PKI module I was forced to rename the command by adding `Ex` suffix just to differentiate commands. 

> show there's some overlap

yes, there is some overlap, because Microsoft named their commands as ones in PSPKI. I renamed some commands (where it makes sense), but some are not, because I don't see big value in using Microsoft commands.

Anyway, when importing PowerShell modules (any), you can supply a command prefix, so every command will be unique:
```PowerShell
Import-Module -Name ModuleName -Prefix MyPrefix
```
PowerShell will automatically map prefixed command names to original ones.

**Comment by Crypt32** [comment]
Added a note about relationships: https://github.com/Crypt32/PSPKI/commit/43080b89033b78e7c4a583bf1bbf7284261d8516
