### ISSUE TITLE
Error Install --> PS PKI v3.2.6 "This may indicate that the cabinet file is corrupt"

### ISSUE THREAD

**Issue by heydemar** [Crypt32/PSPKI#8]
Hi, 

i try to install the PKI v3.2.6 with the installer, and get this message..
Can somebody help me? 

Thanks
![13-07-_2017_10-44-03](https://user-images.githubusercontent.com/5207948/28157928-642df7f4-67b8-11e7-9d97-eac471679435.jpg)

**Comment by Crypt32** [comment]
What operating system you are using?

**Comment by heydemar** [comment]
Server 2008 x86 SP2

**Comment by Crypt32** [comment]
The problem is that the installer is singed with SHA256 signature and Windows Server 2008 (non-R2) does not support SHA2 authenticode signature for installers.

Your best solution here is to download ZIP package (from the same CodePlex download page) and extract it to module folder, because it is unlikely I'm going to fix this.

**Comment by admloic** [comment]
I have the same problem, for install PS PKI V3.2.6, I am on windows server 2008 R2.
Do you have an idea to solve the problem ?
Thanks

**Comment by Crypt32** [comment]
Added a Windows Server 2008 compatible installer: https://pspki.codeplex.com/releases/view/625365
